### ISSUE TITLE
Error: Error: Geolocation system disabled.

### ISSUE THREAD

**Issue by alexbonhomme** [alexetmanon/vliller#35]
https://sentry.io/alex-et-manon/vliller/issues/295044118/

```
Error: Error: Geolocation system disabled.
  at None (../../webpack/bootstrap 0b245e889ea2783906b3:15)
  at t.invoke (/polyfills.js:3:9283)
  at Object.onInvoke (../../webpack/bootstrap 0b245e889ea2783906b3:2)
  at t.invoke (/polyfills.js:3:9223)
  at r.run (/polyfills.js:3:4452)
...
(6 additional frame(s) were not displayed)
```

**Comment by alexbonhomme** [comment]
Corrigé dans 17cfc2a3a78d5d6e0b37d8d232db9e9b85c5e8bc
