### ISSUE TITLE
Error: [object Object] (in handleLocationError)

### ISSUE THREAD

**Issue by alexbonhomme** [alexetmanon/vliller#36]
https://sentry.io/alex-et-manon/vliller/issues/301286127/

```
Error: [object Object]
  at t.handleLocationError (../../webpack/bootstrap 0b245e889ea2783906b3:15)
  at None (../../webpack/bootstrap 0b245e889ea2783906b3:15)
  at t.invoke (/polyfills.js:3:9283)
  at Object.onInvoke (../../webpack/bootstrap 0b245e889ea2783906b3:2)
  at t.invoke (/polyfills.js:3:9223)
...
(7 additional frame(s) were not displayed)
```

**Comment by alexbonhomme** [comment]
Nettoyage des issues qui ne sont plus d'actualité après la réécriture du code en version `2.4.0`.
