### ISSUE TITLE
Error: cancelled

### ISSUE THREAD

**Issue by alexbonhomme** [alexetmanon/vliller#37]
https://sentry.io/alex-et-manon/vliller/issues/300670626/

```
Error: cancelled
  at None (../../webpack/bootstrap 0b245e889ea2783906b3:14)
  at onInvoke (../../webpack/bootstrap 0b245e889ea2783906b3:2)
  at run (/polyfills.js:3:4458)
  at None (/polyfills.js:3:14079)
  at onInvokeTask (../../webpack/bootstrap 0b245e889ea2783906b3:2)
...
(4 additional frame(s) were not displayed)
```

**Comment by alexbonhomme** [comment]
Nettoyage des issues qui ne sont plus d'actualité après la réécriture du code en version `2.4.0`.
