### ISSUE TITLE
Error: Response with status: 400 Bad Request for URL: https://doorbell.io/api/applications/4561/submit?k...

### ISSUE THREAD

**Issue by alexbonhomme** [alexetmanon/vliller#60]
https://sentry.io/alex-et-manon/vliller/issues/398616465/

```
Error: Response with status: 400 Bad Request for URL: https://doorbell.io/api/applications/4561/submit?key=g9xKf3v4aM29diiMXJVh2Ko9J54fEaQ6uCqysESJSf8WWaKIcXwmVBXT94rXF8Lr
  at None (/main.js:1:109862)
  at error (/vendor.js:1:987994)
  at a (/vendor.js:1:409649)
  at i (/vendor.js:1:966337)
  at onInvokeTask (/vendor.js:1:9970)
...
(4 additional frame(s) were not displayed)
```

**Comment by alexbonhomme** [comment]
Fix f08807ae1c3df0fb448da1cbf1567f80933082e6
